### ISSUE TITLE
iOS implementation

### ISSUE THREAD

**Issue by jackbayliss** [jackbayliss/cordova-plugin-stripe-intent#2]
As the title suggests, an iOS implementation of this would be good.

**Comment by Mapiac** [comment]
Any progress on iOS?

**Comment by jackbayliss** [comment]
@Mapiac  I had it mostly working, just didn't know how to close the window so I decided against using a custom plugin such as this.

I ended up using In App Browser to create and generate a payment page using Stripe, I pass in the product and then grab in via the DB on the site so that there's no way it can be tampered with.  So, my suggestion would be the same. Use the In App Browser plugin and handle it that way- if you're using iOS or Android.

For example

```
        var url = "https://www.example.com/create/paymentblah/" + token + "/" + user.id + "/" +_product.id;
        var brower = this.browser.create(url,"_blank");
        brower.on("exit").subscribe(event => {
          that.checkProductForUpdates();
       });

```

**Comment by Mapiac** [comment]
@jackbayliss thanks. We were thinking about using and extending it but maybe you are right and have a better approach. Closing the window was the issue hmm. The issue for us is deciding to extend a plugin like this OR do what you do, but part of the issue is we also need setup intent, not just payment intent https://stripe.com/docs/payments/save-and-reuse

**Comment by jackbayliss** [comment]
@Mapiac  In that case, I'd definitely recommend the in app browser approach. Just make the web page look similar style to the app and bingo. I use the in app browser method for subscriptions and payment intents.  That way you don't have to manage two different versions of the app :)

**Comment by Mapiac** [comment]
@jackbayliss good call. The biggest issue with that (for us) however is a potential hole in the flow with using the inapp browser method, which is that the page redirect after the transaction and getting information back into the app. Example;

1) Making and hosting the webpage (not hard)
2) our version of the "checkForUpdates" method must resolve before user flow can continue
3) There's a step after confirming the card that requires the response from Stripe to continue
4) As we have it now, we can get the value of the response from Stripe because the Ajax request originates within the app. But if it's from another webpage then we can't get it directly.

So if the checkForUpdates network request fails or doesn't resolve in a timely manner then we won't have the card info to proceed with, even though the user has already saved their card info.

**Comment by jackbayliss** [comment]
@Mapiac  
1. I used Vue JS and Stripe Elements so that it's simple and quick flowing.
2. You could show perhaps an alert with `enableBackdropDismiss:false`  before opening the in app browser so that the user can't dismiss it until you're done checking what you need to on browser close.

3. For me, I did all the checks via the website so i.e when the page is hit, it grabs the parameters from the url i.e the user_id, product_id and checks that they can purchase it etc- then presents the view. Once the payment is done etc, it then hits the stripe api and makes sure it's and good- if everything checks out it, it unlocks the product for the user and presents "payment authorised". It then asks them to close the in app browser. When the browser is then closed, I run my check on the app to check for a change in product status- so that if they've purchased something it's now unlocked.  So, for me I didn't even need to pass a value back to the app as everything is done via the website.

4.  It depends on how you've structured your products and app in general -  what exactly you're purchasing etc but potentially you could save any additional data you NEED to send back to the app into a database field etc and then retrieve it via HTTP such as : 

```
  this.http.get('http://mywebsitesapi.com', {user_id:'',token:''}, {})
  .then(data => {
    console.log(data.status);
    console.log(data.data); // data received by server
    console.log(data.headers);

  })
  .catch(error => {

    console.log(error.status);
    console.log(error.error); // error message as string
    console.log(error.headers);

  });
```
In the case of a network error your data wouldn't of been updated, so the user would just get an error message of your choice. But, that would also happen with a custom cordova plugin too.  

All in all, You shouldn't technically need to pass anything back to the app via the browser itself as the 'checkForUpdates' function would automatically update the items to say if it's been purchased or unlocked. 

I hope that kind of made sense, again I'm just throwing a lot of ideas at you- but it's your choice at the end of the day. I'm not too sure how your app functions, but it should be possible via the In App Browser.

**Comment by Mapiac** [comment]
Hmm thanks @jackbayliss great insights too.

I think if the network request fails is an issue there as the user may save the card on the website, come back to the app, and on trying to fetch the info within the app that request may fail. And in some parts of our flow, like when a user orders, we can't proceed until we're sure there's a payment method saved. We have to decide how to proceed in such a scenario if we go the external route. Is this a concern ever for you? Right now the way I see it is to tell the user something went wrong and not proceed. But that would be quite an inconvenience and bad/confusing UX because we'd likely have the webpage give some sort of signal to the user that the card was saved successfully.

**Comment by jackbayliss** [comment]
@Mapiac 

It's not an issue for me, my products work with an 'unlocked' state. So when the user clicks to see their products etc there's a call made to my API to grab each of the products. On the app if a product is locked it'll set it to such and they can choose to pay for it and unlock it etc where as if it's unlocked a different function is run on click. So, even if the call to pay fails once the window is closed the product will remain locked until they've paid for it. In terms of UX/ UI experience actual calls should never really fail unless there's an actual issue with the service i.e Stripe or your entire API is going down. In terms of a full failure I decided to show a toast saying 'Please try again in the next 30 minutes'. My app as a whole depends on internet usage mostly, so when the internet is disconnected a page shows to say 'Please turn on your internet blah blah'

In your situation you could save a copy of the order before you even call in the app browser in local storage or on your db, so if anything does go wrong within the payment it will still exist- either via an api or local storage. 

If you get an error state back from the API on the payment call you could either:
1.via the DB show the order as an 'incomplete' state on their profile and just say "Expecting your payment method" so they can try again to complete it.
2. Save it in local storage such as incomplete_order, so that the user can see there's an incomplete order- however on app delete etc this wouldn't exist. 
3. Send an email to the user via the API (if it's a stripe faliure you can catch it) with a link to retry.
4. If it's a complete service failure of your site offer an error message, or have your app hit a different secondary URL.

If I were you I'd probably just show the order as incomplete on failure, so it just pops up an alert at the top to say "Your order didn't go through successfully, try again in the next 15 minutes.". But like I said failures should not happen often, and with services such as Digital Ocean / AWS etc they have failover solutions etc so if your whole site went down it should automatically change machine and come back up within minutes.

I hope this kind of helped, there's always a way to do things it's just the way that works for you. I know you're worried about the user's UX but, for example even if you used the cordova-stripe-plugin if there's a service failure between you and Stripe it would be the same. Stripe would just say "Try again in 30 minutes" or "We're having issues etc". It's just handling them as best possible.

**Comment by stefanotauriello** [comment]
> @Mapiac I had it mostly working, just didn't know how to close the window so I decided against using a custom plugin such as this.
> 
> I ended up using In App Browser to create and generate a payment page using Stripe, I pass in the product and then grab in via the DB on the site so that there's no way it can be tampered with. So, my suggestion would be the same. Use the In App Browser plugin and handle it that way- if you're using iOS or Android.
> 
> For example
> 
> ```
>         var url = "https://www.example.com/create/paymentblah/" + token + "/" + user.id + "/" +_product.id;
>         var brower = this.browser.create(url,"_blank");
>         brower.on("exit").subscribe(event => {
>           that.checkProductForUpdates();
>        });
> ```

Is it compatible with Play Store and Apple Store guidelines? If I use iframe instead of In App Browser?

**Comment by jackbayliss** [comment]
@stefanotauriello No, technically it's not allowed. . And if it's for unlocking content etc then you have to technically go via IAP, see  [this](https://developer.apple.com/app-store/review/guidelines/) I'm not sure about Google, but I'm sure it's along the same lines. Closing this- as it's only really a good idea for some kind of in house app. This plugin won't be updated as payments must go via their respective stores.
